let data = [
  {
    machine_name: "Auto machine",
    machine_id: "machine001",
    current: 0,
    voltage: 0,
    power_factor: 0,
    active_power: 0,
    apparent_power: 0,
    reactive_power: 0,
    daily_energy: 0,
    monthly_energy: 0,
    yearly_energy: 0,
    idle_daily: 0,
    idle_monthly: 0,
    idle_yearly: 0,
  },
  {
    machine_name: "Bioler Machine",
    machine_id: "machine004",
    current: 0,
    voltage: 0,
    power_factor: 0,
    active_power: 0,
    apparent_power: 0,
    reactive_power: 0,
    daily_energy: 0,
    monthly_energy: 0,
    yearly_energy: 0,
    idle_daily: 0,
    idle_monthly: 0,
    idle_yearly: 0,
  },
];

export default data;
